### ISSUE TITLE
Sample of entries for Cisco Managed Bucket

### ISSUE THREAD

**Issue by mario5046** [rafaelsampaio/UmbrellaLogstashPipeline#1]
Hello
Could you provide samples for variables to gather logs from Cisco Managed Bucket ?

**Comment by rafaelsampaio** [comment]
Hi! Look this [doc](https://docs.umbrella.com/deployment-umbrella/docs/cisco-managed-s3-bucket). In the end of step 3, you can see all that info that you need.

`AWS_ACCESS_KEY_ID`: provided by Cisco when you complete the activation.
`AWS_SECRET_ACCESS_KEY`: provided by Cisco when you complete the activation.
`AWS_S3_BUCKET`: the string before the / in Data Path that Cisco provided when the activation is completed. Usually, it’s something like “cisco-managed-[region]"
`AWS_S3_REGION`: the region that you chose when configuring data retention in Umbrella.
`AWS_S3_PREFIX`: the string after the / in Data Path that Cisco provided when the activation is completed. It's something like your account number plus a large id.
